name: ThinkFast
options:
  bundleIdPrefix: dev.sadakat
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  createIntermediateGroups: true

settings:
  base:
    PRODUCT_NAME: ThinkFast
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    INFOPLIST_FILE: ThinkFast/Resources/Info.plist
    PRODUCT_BUNDLE_IDENTIFIER: dev.sadakat.thinkfast
    CODE_SIGN_ENTITLEMENTS: ThinkFast/Resources/ThinkFast.entitlements
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: "3FKXUW9MS9"
    ENABLE_PREVIEWS: YES

targets:
  ThinkFast:
    type: application
    platform: iOS
    sources:
      - ThinkFast
    settings:
      base:
        INFOPLIST_FILE: ThinkFast/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: dev.sadakat.thinkfast
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseFirestore
      - package: Facebook
        product: FacebookLogin
      - package: Facebook
        product: FacebookCore

  ThinkFastTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - ThinkFastTests
    dependencies:
      - target: ThinkFast

  ThinkFastUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - ThinkFastUITests
    dependencies:
      - target: ThinkFast

  ThinkFastWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - ThinkFastWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.sadakat.thinkfast.widget
        INFOPLIST_FILE: ThinkFastWidget/Info.plist
        EXTENSION_SUFFIX: .appex
        EXTENSION_POINT_IDENTIFIER: com.apple.widgetkit-extension
    dependencies:
      - target: ThinkFast

  DeviceActivityReportExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - DeviceActivityReportExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.sadakat.thinkfast.DeviceActivityReport
        INFOPLIST_FILE: DeviceActivityReportExtension/Info.plist
        EXTENSION_SUFFIX: .appex
        EXTENSION_POINT_IDENTIFIER: com.apple.deviceactivity.report-extension
    dependencies:
      - target: ThinkFast

schemes:
  ThinkFast:
    build:
      targets:
        ThinkFast: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - ThinkFastTests
        - ThinkFastUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: "10.24.0"
  Facebook:
    url: https://github.com/facebook/facebook-ios-sdk.git
    from: "17.0.0"
