name: Intently
options:
  bundleIdPrefix: dev.sadakat
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  createIntermediateGroups: true

settings:
  base:
    PRODUCT_NAME: Intently
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    INFOPLIST_FILE: Intently/Resources/Info.plist
    PRODUCT_BUNDLE_IDENTIFIER: dev.sadakat.intently
    CODE_SIGN_ENTITLEMENTS: Intently/Resources/Intently.entitlements
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: "3FKXUW9MS9"
    ENABLE_PREVIEWS: YES

targets:
  Intently:
    type: application
    platform: iOS
    sources:
      - Intently
    settings:
      base:
        INFOPLIST_FILE: Intently/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: dev.sadakat.intently
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseFirestore
      - package: Facebook
        product: FacebookLogin
      - package: Facebook
        product: FacebookCore

  IntentlyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - IntentlyTests
    dependencies:
      - target: Intently

  IntentlyUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - IntentlyUITests
    dependencies:
      - target: Intently

  IntentlyWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - IntentlyWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.sadakat.intently.widget
        INFOPLIST_FILE: IntentlyWidget/Info.plist
        EXTENSION_SUFFIX: .appex
        EXTENSION_POINT_IDENTIFIER: com.apple.widgetkit-extension
    dependencies:
      - target: Intently

  DeviceActivityReportExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - DeviceActivityReportExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.sadakat.intently.DeviceActivityReport
        INFOPLIST_FILE: DeviceActivityReportExtension/Info.plist
        EXTENSION_SUFFIX: .appex
        EXTENSION_POINT_IDENTIFIER: com.apple.deviceactivity.report-extension
    dependencies:
      - target: Intently

schemes:
  Intently:
    build:
      targets:
        Intently: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - IntentlyTests
        - IntentlyUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: "10.24.0"
  Facebook:
    url: https://github.com/facebook/facebook-ios-sdk.git
    from: "17.0.0"
